# Generated by Django 5.2.6 on 2025-12-05 08:41

import django.db.models.deletion
import quiz.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название квиза')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='описание квиза')),
            ],
            options={
                'verbose_name': 'квиз',
                'verbose_name_plural': 'квизы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='текст вопроса')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='описание вопроса')),
                ('options', models.JSONField(help_text='должно быть 2 или более вариантов', validators=[quiz.validators.validate_options], verbose_name='варианты ответа')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='правильный ответ')),
                ('explanation', models.CharField(blank=True, max_length=250, null=True, verbose_name='объяснение ответа')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=6, verbose_name='сложность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category', verbose_name='Категория')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='квиз')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ['difficulty', 'id'],
                'default_related_name': 'questions',
            },
        ),
    ]
